# Site settings
title: AmBeta Blog
SEOTitle: 三土的博客 | AmBeta Blog
header-img: imgs/header-bg.png
header-thumb: imgs/my-thumb.png
email: cyandrewchen@gmail.com
description: "AmBeta's personal tech blog."
keyword: "Front-end Web, JavaScript, HTML, CSS"
url: "http://ambeta.github.io"  # your host, for absolute URL
baseurl: ""                     # for example, '/blog' if your blog hosted on 'host/blog'

# Build settings
encoding : utf-8
timezone: Asia/Shanghai
gems: [jekyll-paginate]
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SNS settings
RSS: false
weibo_username:     andrewidiot
#zhihu_username:    AmBeta
github_username:    ambeta
#twitter_username:  AmBeta
#facebook_username: AmBeta
duoshuo_username:   ambeta

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Analytics settings
# Baidu Analytics
#ba_track_id: serial-number
# Google Analytics
ga_track_id: 'UA-75340276-2'            # Format: UA-xxxxxx-xx
ga_domain: ambeta.github.io